### ISSUE TITLE
Rename user timestamp fields to snake case

### ISSUE THREAD

**Issue by timmyichen** [timmyichen/dev-directory#100]
**Description**
Sequelize uses `createdAt` and `updatedAt` as names for timestamp columns. This is not ideal because the convention for sql/postgres is to use snake_case (as column names are case insensitive), so we should probably follow that convention.

This will require a migration, and ideally will not break existing user data.

Some app downtime will be required for this app, such is life. Bonus points for the taker of this ticket if you can also describe how to make the change _without_ any app downtime.

**Acceptance Criteria**
* User model uses `created_at` and `updated_at` for timestamps
* Existing user data is preserved

**Comment by ujwalkumar1995** [comment]
Hey @timmyichen 
I can work on this issue. Regarding downtime, I have not gone through the code base in depth but could you please elaborate on why would you need a downtime if we rename these columns?

**Comment by timmyichen** [comment]
> Regarding downtime, I have not gone through the code base in depth but could you please elaborate on why would you need a downtime if we rename these columns? 

For sure! So this requires some knowledge of how the deployment process works. I'm in mobile but will do my best.  In the package.json there is a heroku postbuild script that runs to build the app. This happens before the server is restarted with the new build. So the timeline of events is:

- old server code relies on createdAt
- migration runs, renaming the column
- between now and when the server is able to restart, any attempts to access or create a user will fail since the createdAt column no longer exists
- once the server code is re deployed everything is okay again

So the downtime is short, but in a production environment it can be risky because what if you run the migration, then the server code failed to deploy? Or if the new server code had bugs and we had to roll back? For this app in particular its not a concern but this is something good to think about / to be able to identify or talk about in interviews

**Comment by ujwalkumar1995** [comment]
Hwy @timmyichen 
Thank you for such a detailed description of the problem.
I understood the issue on a high level but deployment related challenges is not my strongest suit. Anyways I have submitted a PR for the dev related changes. Please look at it. If someone else has a better solution, even I would be willing to learn from it.
