### ISSUE TITLE
Create simple page for a profile

### ISSUE THREAD

**Issue by timmyichen** [timmyichen/dev-directory#11]
Project: #19 
Depends on: #9 

**Description**
There are no designs yet for this, so just do whatever's simplest and looks just okay.  When a user navigates to `/profile/:id`, they should be shown that user's profile.  Use the newly created route in #9 to fetch the data.  No need to display the user's internal `id`.  Use the user's `discord_name` as the main heading.

The user's profile should be server-side-rendered, so there should be no loading state.

You'll probably have to add a new server-side router to handle page routes; unless there's a better nextjs-way of doing this when the page name is also a parameter.

**Acceptance Criteria**
* The page exists and is server-side rendered
* The page displays all of the user's information returned from the GET endpoint

**Comment by devonzara** [comment]
Initial groundwork is done... blocked on #8.
