### ISSUE TITLE
Tech Spec: Developer Profiles

### ISSUE THREAD

**Issue by timmyichen** [timmyichen/dev-directory#3]
**Summary:**
Developers should be able to put up information about themselves. This tech spec represents a basic UI for displaying a user's profile, and providing that user the ability to edit it.

**Scope:**
* Changes to the model and migrations to support profile data
* Simple UI for showing a user's profile
* Simple UI for editing a user's own profile

**Data model:**
New tables: N/A
Modified tables: the `users` table:
* Add a column `discord_name` representing their discord username + discriminator, e.g. `chimten#3819` (string, max 100 chars)
* Add a column `bio` representing their bio (string, max 1000 chars)
* Add the columns representing their social links:
  * `twitter` (string, max 200 chars)
  * `linkedin` (string, max 200 chars)
  * `github` (string, max 200 chars)
  * `website` (also used for their portfolio) (string, max 500 chars)

New columns should be validated and checked for a maximum length before saving to the database.

**User Stories:**
* Users will be able to edit their own bio on their profile
* Users will be able to add social links to their profile
* Users will be able to view other peoples' profiles

**Features:**
Two new pages/views:
* View a specific user's profile
* Edit your own profile

**APIs:**
A new `users` router will be created to handle the following endpoints:
1. `GET /api/users/:id` - gets a user's public profile details + socials
  * If the caller is logged in, they will receive the requested user's `discord_name`
2. `PATCH /api/users/:id` - updates a subset of user profile columns. Should only be allowed for the currently-logged-in user.

**Security:**
* User inputs should be sanitized to not include any markup (even though React won't render it)
* User inputs should have an enforced maximum length to prevent large pieces of data inserted into the DB
* Route 1 should not return the `discord_name` if the caller is not authed
* Route 2 should only allow specific columns to be updated

**Testing:**
For now, just acceptance tests on the server via jest to test the endpoints.  End-to-end tests can wait until we have a more fleshed out design.

**Open Questions**
How should the profile path be structured?  e.g. `domain.com/profile/:userId`? or `domain.com/profile/:discordId`? Open to suggestions here.

**Deployment:**
Migrations will need to run prior to release. Existing data will not be impacted.

**Comment by timmyichen** [comment]
Future improvements:
* More granular privacy settings

Re profile path:
* Be sensitive to users who may not want their 100devs status to be public
* Start with internal db user ID, continue discussion here from discord

**Comment by devonzara** [comment]
**APIs:**
Thoughts on pluralizing our collection nouns and `PATCH`ing to the same endpoint URI? eg.
1. `GET /api/users/:id` - gets a user's public profile details + socials
2. `PATCH /api/user/:id` - updates a subset of user profile columns, applied to the currently-logged-in-user.

**Future improvements:**
- Ability for users to mark their entire profile as private; this should make it invisible to anyone who is not logged in.  

  **Reason**: Some people might want to connect with community developers without revealing their affiliation or desire for a career change to the public.

**Comment by timmyichen** [comment]
Good call re pluralizing - it's more RESTful - updated!

**Comment by timmyichen** [comment]
Closed via #19
