### ISSUE TITLE
Production should use `process.env.DATABASE_URL` instead of individual components

### ISSUE THREAD

**Issue by timmyichen** [timmyichen/dev-directory#32]
**Description**
Heroku may sometimes do maintenance work on our database, which may change its credentials.  This is annoying but we can't really avoid it cause we're on the cheapest tier DB.  When they do this, they automatically update the DATABASE_URL environment variable for the project.

To avoid Heroku doing maintenance breaking our app, we should, in production, use `process.env.DATABASE_URL` instead of using the port/host/user/etc individually.  This should be used both when we initialize Sequelize in `server/lib/db`, as well as where we set Sequelize configurations in `server/config/config`.

**Acceptance Criteria**
* Development and test environments use the port/host/user environment variables
* Production uses DATABASE_URL environment variables

**Comment by jmoldyvan** [comment]
I think I can do this, I'll let someone know if i need help

**Comment by timmyichen** [comment]
Thanks for taking this on!  We lean heavily into [envalid](https://www.npmjs.com/package/envalid) when processing environment variables, we can probably do the same here!

**Comment by devonzara** [comment]
> we should, in production, use process.env.DATABASE_URL

> Production uses DB_URL environment variables

To alleviate any possible confusion, should the acceptance criteria specify `DATABASE_URL` or `DB_URL`?

**Comment by timmyichen** [comment]
> To alleviate any possible confusion, should the acceptance criteria specify `DATABASE_URL` or `DB_URL`?

Oops, thanks for catching - it's `DATABASE_URL` (set by heroku)
