### ISSUE TITLE
Remove endpoint for getting a user's profile

### ISSUE THREAD

**Issue by timmyichen** [timmyichen/dev-directory#33]
**Related Issues**
Project: #19 
Depends on: #9 

**Description**
The existing endpoint isn't very RESTful and it'll probably need to be replaced with the "get all users" functionality introduced in #17 .  So once #9 is completed, we'll use that for getting a user's profile.

Right now, we make a call to that endpoint to determine whether they're logged in [here](https://github.com/timmyichen/dev-directory/blob/760bb5e233473482d4f80f7bba92e37d328bd57b/pages/index.tsx#L56).  Once we remove the current route, we'll need to update this to use the route created in #9, which will require extracting the user's ID from the jwt auth token stored as a cookie.

The task is:
* Remove the existing `/api/users/` API endpoint
* Update the endpoint called in `index.tsx` to the new endpoint created in #9, using the cookie jwt auth token to determine the currently-logged-in-user's ID.

**Acceptance Criteria**
* Existing `/api/users/` endpoint is removed
* The app can still detect whether someone is logged in or not

**Comment by timmyichen** [comment]
@windyScripts i added the high priority label since it's blocking the pagination project - do you think you'd be able to work with someone to ship it in the 2-3 days?  otherwise are you okay with allowing someone else to take this on?  just want to make sure that the big projects can still move forward in a timely manner

**Comment by windyScripts** [comment]
Will get this done.

**Comment by Caleb-Cohen** [comment]
What made the previous API endpoint not very restful?
