### ISSUE TITLE
Create seed script that inserts users into the database

### ISSUE THREAD

**Issue by timmyichen** [timmyichen/dev-directory#39]
**Related Issues**
Depends on: #38

**Description**
Since dev relies on discord auth, it would be nice if there were a bunch of users already included in the database since we can't realistically manually create a bunch of users.

Using the `createUser` test utility function, let's create a file `server/scripts/seed.ts` that creates 100 random users and inserts them into the database.  This should be done within a [transaction](https://sequelize.org/docs/v6/other-topics/transactions/#managed-transactions) so that if it fails, it doesn't insert any data.

**Acceptance Criteria**
* `npm run seed` exists as a script, and running it inserts 100 random users into the database.

**Comment by jmoldyvan** [comment]
ill try this one!

**Comment by timmyichen** [comment]
> ill try this one!

Still depends on #38 which is currently in review!

**Comment by jmoldyvan** [comment]
> > ill try this one!
> 
> Still depends on #38 which is currently in review!

I'll wait until it gets completed

**Comment by MainlyColors** [comment]
I just merged my PR #48 that closes ticket #38 so your good to start this 🚀🚀🚀

**Comment by jmoldyvan** [comment]
Sounds good I'll start working on it

**Comment by Caleb-Cohen** [comment]
Hey @jmoldyvan, where are we at with this? I could really use it for #58.

**Comment by jmoldyvan** [comment]
> Hey @jmoldyvan, where are we at with this? I could really use it for #58.

Just got my PR in, had some trouble and then some internet trouble.
I also updated the utils createUser function so that a bulkCreate would be possible, which may or may not be useful for #58
