### ISSUE TITLE
Modify `/api/users` API route to support pagination

### ISSUE THREAD

**Issue by DevinCLane** [timmyichen/dev-directory#58]
**Related Issues**
- Project: #17 
- Depends on: #57  

**Description**
- Modify `/api/users` API route to support pagination using the Offset API Pagination
- This route needs to support a `page` query parameter.
- Limit the API route to return 20 profiles.
- Return which page we're on and the total pages available in the database.

[Read more about Offset API Pagination](https://nordicapis.com/understanding-5-types-of-web-api-pagination/#offset-api-pagination)

**Acceptance Criteria**
- The `/api/users` route can be paginated, returning 20 users at a time.
- Acceptance tests exist.

**Comment by Caleb-Cohen** [comment]
Why is `page` query parameter needed? Won't this be used for an infinite scroll?

**Comment by timmyichen** [comment]
> Why is `page` query parameter needed? Won't this be used for an infinite scroll? 

When the server receives the request, how does it know which set of users to return?

**Comment by Caleb-Cohen** [comment]
> > Why is `page` query parameter needed? Won't this be used for an infinite scroll?
> 
> When the server receives the request, how does it know which set of users to return?

Good point. Ready for review: https://github.com/timmyichen/dev-directory/pull/73
