### ISSUE TITLE
Display user profiles returned from `/api/users` route

### ISSUE THREAD

**Issue by DevinCLane** [timmyichen/dev-directory#59]
**Related Issues**
- Project: #17 
- Depends on: #58  

**Description**
- Display user profiles returned from `/api/users` route on home page.
- Show Discord names for each user.

**Acceptance Criteria**
- User profiles are shown on the home page.
- Acceptance tests exist for this feature.

**Comment by timmyichen** [comment]
On further thought, we should probably create a separate page for this; being able to use the home page to introduce the app seems like something we'd want to do.  maybe `/directory`?

**Comment by DevinCLane** [comment]
Hm yeah. I was imagining the first point of contact being the Login page that has a short description of what the app is/does, and then once you log in, you have the directory. Open to what you're describing though too.

**Comment by Caleb-Cohen** [comment]
Client-side testing goes where?

**Comment by devonzara** [comment]
Are we set on `/directory`? Thoughts on `/browse`, `/developers`, or even just `/search`?

**Comment by timmyichen** [comment]
I'm fine with any of them; it can easily be changed from one to the other.
