### ISSUE TITLE
Implement Infinite Scroll

### ISSUE THREAD

**Issue by DevinCLane** [timmyichen/dev-directory#60]
**Related Issues**
- Project: #17  
- Depends on: 
  - #58 
  - #59   

**Description**
- Use [Intersection Observer](https://www.freecodecamp.org/news/how-to-implement-infinite-scroll-in-next-js/) to trigger loading of a new batch of 20 profiles on the home page when the user scrolls down.
- Ensure we don't load pages that don't exist (i.e., if the server tells us we have 5 total pages, we never request a 6th page.)
- The user should see that the next batch of pages is loading (i.e., there is a loading state visualized).
- A page is never loaded twice. 
- When loading the next page, we are not fetching an extra batch of pages (i.e., if the user triggers a new load, then scrolls up and back down before the loading completes, we do not trigger loading a new batch of pages).

**Acceptance Criteria**
- A new batch of 20 profiles is displayed when the user scrolls down.
- We don't load pages that don't exist.
- The user sees a loading state when a new batch of pages is loading.
- A page is never loaded twice.
- One batch of pages is loaded at a time.
- Acceptance tests exist for this issue.

**Comment by MainlyColors** [comment]
Ill attempt this 👀
