### ISSUE TITLE
Create OnBoarding Page and Skip Functionality

### ISSUE THREAD

**Issue by jmoldyvan** [timmyichen/dev-directory#76]
**Related Issues**
- Project: #23
- Depends on: N/A

**Description**
- Use MUI to create a new page where users are redirected to, after they log in. 
- Create a dismiss button that will redirect users to the dev-directory list of profiles page.

**Acceptance Criteria**
The new page is created and the dismiss button is functional.
Redirection from the discord login is functional.
Redirection from onboarding to the dev-directory list of profile pages is functional.

**Comment by MainlyColors** [comment]
> Create a dismiss button that will redirect users to the dev-directory list of profiles page.

Currently, this is just the home page route `/` since we don't have a route for showing dev-directory of profiles yet, But I assume that will also be on the `/` home route

**Comment by devonzara** [comment]
As mentioned in #82:
- `OnBoarding` should be `Onboarding` as it's a single word
- `dismiss` should be changed to `skip` since we're working with pages and not modals
