### ISSUE TITLE
Create Flags That Check If User Has Been Through Onboarding

### ISSUE THREAD

**Issue by jmoldyvan** [timmyichen/dev-directory#78]
**Related Issues**
- Project: #23
- Depends on: 
  - #76

**Description**

Add an additional table `flags` that has the following schema:
* `user_id` foreign key to `users (id)`
* `flag_name` that represents the flag we are setting.

Once the user has skipped or completed onboarding, insert a new row in the `flags` tables, for example: `(user1, 'hasBeenOnboarded')`

Add additional routes for fetching a user's flags:
```js
const flags = await Flags.findAll({ where: { user_id: user.id } });
return flags.map(flag => flag.flag_name);
```

**Acceptance Criteria**
Make sure the tables are created.
Have the tables new rows created.
The new routes are functional.

**Comment by DevinCLane** [comment]
I'll take a crack at this
