### ISSUE TITLE
Add Redirect For Users That Have Been Through Onboarding

### ISSUE THREAD

**Issue by jmoldyvan** [timmyichen/dev-directory#79]
**Related Issues**
- Project: #23
- Depends on: 
  - #78

**Description**
- Include the logic to redirect users to the dev-directory list page after login, based on the flags created in #78.

**Acceptance Criteria**
Users who have the specified flag from #78 will be redirected without seeing the onboarding.

**Comment by jmoldyvan** [comment]
I can grab this once #78 is done

**Comment by timmyichen** [comment]
This might actually [be done](https://github.com/timmyichen/dev-directory/commit/b37b5be350ebb578bc1a11a41176aab88bf0c08f#diff-ac7d80d71d40a2b128439c34595c6c71b51f562fd55ec73eaf7f358f6f00eeeeR18-R21), @jmoldyvan - let me know if you find otherwise!

**Comment by jmoldyvan** [comment]
YUP! Looks like the functionality for skipping has been introduced! This issue is completed @timmyichen
