### ISSUE TITLE
Feature: Greeting On Login Page

### ISSUE THREAD

**Issue by jmoldyvan** [timmyichen/dev-directory#80]
**Related Issues**
- Project: #23
- Depends on: 

**Description**

- Use the MUI to create a simple block of text on the same page as the DiscAuth Login

- Create a greeting for users that briefly explains what PairUp is, what we aim to accomplish, and welcomes new users.

**Acceptance Criteria**
Users can still login

**Comment by timmyichen** [comment]
Correct me if wrong, but I don't think we actually have the ability to do this? The discord OAuth page is handled by discord; we can't choose what to display on that page.

**Comment by jmoldyvan** [comment]
Oh, ok, I thought we could manipulate that.

**Comment by DevinCLane** [comment]
Would we just add this description to our landing page/login page then?

**Comment by thecornisians** [comment]
I want to pick up this issue if no one has yet

**Comment by windyScripts** [comment]
Modals like those of discord and even payment gateways like stripe are designed to be secure from tampering, whether it be from the user, the host website or any other entity. This is why on opening the modal, the user's capacity to interact with the parent page is disabled entirely, and also why the modals themselves cannot be changed visually/mechanically.

*Just leaving this here in case anyone wondered why this is the case*

**Comment by jmoldyvan** [comment]
should I update this ticket or close?

**Comment by timmyichen** [comment]
We can probably close this issue imo - closing out the project!
