### ISSUE TITLE
Add API endpoint for getting a user's profile

### ISSUE THREAD

**Issue by timmyichen** [timmyichen/dev-directory#9]
Project: #19 
Depends on: #8 

**Description**
This issue adds an API endpoint for getting a user's profile.

Add an API endpoint:
* `GET /api/users/:id`

This endpoint should return all of a user's information sans `email`:
* `id`
* `bio`
* `discord_name`
* social links added in #8 

Use an allow-list of fields to include so as to not accidentally leak fields added in the future.

**Acceptance Criteria**
* API endpoint exists
* New acceptance tests exist and pass
* Existing tests pass

**Comment by Caleb-Cohen** [comment]
I'm the captain now
