### ISSUE TITLE
Snackbar error handling

### ISSUE THREAD

**Issue by timmyichen** [timmyichen/dev-directory#98]
**Description**
We want to create a way for any part of the app to surface errors.  [Notistack](https://github.com/iamhosseindhv/notistack) does this pretty well.
* Alerts should support dismissing them, [example](https://notistack.com/features/basic#actions)
* It should support different kind of snackbars. Here are the [props](https://notistack.com/api-reference#mutual-props)

It would also be nice if we had a react hook that returns helper functions for enqueueing any success/error/warning/info.  So the actual usage would look something like this:

```ts
// within a react component
const { showSuccess, showError } = useAlerts();

const onClick = () => {
  try {
    doSomething();
    showSuccess('Thing was successful');
  } catch (err) {
    showError('something went wrong');
  }

  return <Button onClick={onClick}>Do a thing</Button>
}
```

**Acceptance Criteria**
* Notistack is used in the app
* Snackbars can be enqueued from any part of the app
* Abstractions exist via custom hook

**Comment by windyScripts** [comment]
I'll give this a go!
